name: Mi Servidor CI/CD

on:
  push:
    branches: [ "master" ] # Escucha a ambas ramas para asegurar el tiro

jobs:
  compilar-y-desplegar:
    runs-on: ubuntu-latest
    environment: PROD  

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    # 🛠️ CAMBIO CLAVE: Usamos las acciones oficiales del equipo de Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Iniciar sesion en mi Registry Privado
      uses: docker/login-action@v3
      with:
        registry: registry.zsoftsolutions.com
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Compilar imagen y subirla al Registry
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: registry.zsoftsolutions.com/portalweb:latest

    - name: Entrar al servidor por SSH y actualizar
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/asta/docker-compose
          docker login registry.zsoftsolutions.com -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }}
          docker compose -f portalweb.yml pull portalweb
          docker compose -f portalweb.yml up -d --force-recreate portalweb
          docker image prune -f